name: geconpy-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core dependencies
  - python=3.13
  - pip
  - pymc>=6.0.1
  - pytensor>=3.0.4
  - matplotlib
  - numba
  - numpy
  - pandas
  - pyparsing
  - scipy
  - setuptools
  - statsmodels
  - preliz>=0.25.0
  - sympy>=1.14.0
  - pymc-extras>=0.12.0
  - better-optimize>=0.4.2
  - sympytensor>=2.0.1
  - jax
  - nutpie>=0.16.10
  - networkx

  # Extra dependencies for docs build
  - ipython
  - jupyter-sphinx
  - myst-nb
  - numpydoc
  - pre-commit
  - sphinx>=9.1.0
  - sphinx-copybutton
  - sphinx-design
  - sphinx-notfound-page
  - sphinx-sitemap
  - sphinx-codeautolink
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme
  - watermark
