name: geconpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core dependencies
  - python=3.13
  - pymc>=6.0.1
  - pytensor>=3.0.4
  - matplotlib
  - numba
  - numpy
  - pandas
  - pyparsing
  - scipy
  - setuptools
  - statsmodels
  - preliz>=0.25.0
  - sympy>=1.14.0
  - pymc-extras>=0.12.0
  - better-optimize>=0.4.2
  - ipython
  - nutpie>=0.16.10
  - networkx
  - sympytensor>=2.0.1

  - pip:
      - jax>=0.10.1
      - flowjax
