name: run_tests

on:
  pull_request:
    paths:
      - ".github/workflows/run_tests.yml"
      - "conda_envs/**"
  push:
    paths:
      - ".github/workflows/run_tests.yml"
      - "conda_envs/**"
    branches: [main]

jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, mac-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        mamba-version: "*"
        activate-environment: geconpy-test
        channel-priority: strict
        environment-file: conda_envs/geconpy_test.yml
        python-version: 3.9
        use-mamba: true

    - name: Install gEconpy
      run: |
        echo conda env list
        conda activate geconpy-test
        python --version

    - name: Run tests
      run: |
        python -m unittest discover -s tests/ -t tests/
