name: Python Package using Conda

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unittest:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: geconpy-test
          channel-priority: strict
          environment-file: conda_envs/geconpy_test.yml
          python-version: 3.9
          use-mamba: true
    - name: Install gEconpy
      run: |
          conda activate geconpy-test
          python --version
    - name: Run tests
      run: |
        conda activate geconpy-test
        python -m unittest discover -s tests/ -t tests/
