name: run_tests

on:
  pull_request:
    paths:
      - ".github/workflows/run_tests.yml"
      - "conda_envs/**"
  push:
    paths:
      - ".github/workflows/run_tests.yml"
      - "conda_envs/**"
    branches: [main]

jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
        test-subset:
          - |
            gEconpy/tests/test_parser.py

    runs-on: ${{ matrix.os }}

    env:
      TEST_SUBSET: ${{ matrix.test-subset }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      env:
        # Increase this value to reset cache if geconpy_test.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-py${{matrix.python-version}}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('conda_envs/geconpy_test.yml') }}
    - name: Cache multiple paths
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if requirements.txt has not changed
        CACHE_NUMBER: 0
      with:
        path: |
          ~/.cache/pip
          $RUNNER_TOOL_CACHE/Python/*
          ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
          hashFiles('requirements.txt') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        mamba-version: "*"
        activate-environment: geconpy-test
        channel-priority: strict
        environment-file: conda_envs/geconpy_test.yml
        python-version: 3.9
        use-mamba: true
        use-only-tar-bz2: false # IMPORTANT: This may break caching of conda packages! See https://github.com/conda-incubator/setup-miniconda/issues/267

    - name: Run tests
      run: |
        python -m unittest discover -s gEconpy/tests/ -t $TEST_SUBSET
