name: run_tests

on:
  pull_request:
  push:
    branches: [main]


# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true


jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12"]
        exclude:
          - os: ubuntu-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.12"
        test-subset:
          - |
            tests/

    runs-on: ${{ matrix.os }}

    env:
      TEST_SUBSET: ${{ matrix.test-subset }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      env:
        # Increase this value to reset cache if geconpy_test.yml has changed
        CACHE_NUMBER: 4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-py${{matrix.python-version}}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('conda_envs/geconpy_test.yml') }}
    - name: Cache multiple paths
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if requirements.txt has changed
        CACHE_NUMBER: 4
      with:
        path: |
          ~/.cache/pip
          $RUNNER_TOOL_CACHE/Python/*
          ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
          hashFiles('requirements.txt') }}


    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: conda_envs/geconpy_test.yaml
        create-args: >-
          python=${{matrix.python-version}}
        environment-name: geconpy-test
        init-shell: bash
        cache-environment: true

    - name: Install current branch
      run: |
        conda activate geconpy-test
        pip install -e .
        python --version

    - name: Run tests
      run: |
        python -m pytest -vv --cache-clear --cov=gEconpy --cov-report=xml --no-cov-on-fail --cov-report term $TEST_SUBSET
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # use token for more robust uploads
        env_vars: TEST_SUBSET
        name: ${{ matrix.os }}
        fail_ci_if_error: false
        verbose: true
